# Copyright (C) 2024 Nicola Dardanis <nicdard@gmail.com>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, version 3.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <https://www.gnu.org/licenses/>.
#
# Configuration file for the PKI Rocket-based server. See: ./services/pki/README.md
[default]
address = "127.0.0.1"
port = 8001

# https://rocket.rs/guide/v0.5/configuration/#tls
# https://rocket.rs/guide/v0.5/configuration/#mutual-tls
[default.tls]
certs = "private/ds/ds_cert.pem"
key = "private/ds/ds_keys.pem"

[default.tls.mutual]
ca_certs = "private/ca/ca_cert.pem"

# Upload data limits: https://api.rocket.rs/v0.5/rocket/data/struct.Limits#built-in-limits

[default.databases.ds]
url = "mysql://@localhost:3306/ds"

# Custom configuration for the AWS S3 client. Dynamo Db will use same credentials and endpoint url.
[default.s3_storage]
# The test-bucket is accessible here: http://localhost:4566/test-bucket/
bucket = "test-bucket"
endpoint = "https://localhost:4566"
access_key_id = "test"
secret_access_key = "test"

# [global.limits]
# msgpack = "100 MiB"
# string = "100 MiB"
# data-form = "100 MiB"
# file = "100 MiB"
# form = "100 MiB"
# json = "100 MiB"
# bytes = "100 MiB"
