# Configuration file for the PKI Rocket-based server. See: ./services/pki/README.md
[default]
address = "127.0.0.1"
port = 8001

# https://rocket.rs/guide/v0.5/configuration/#tls
# https://rocket.rs/guide/v0.5/configuration/#mutual-tls
# TLS and mutual TLS configuration are added programmatically

[default.databases.ds]
url = "mysql://@localhost:3306/ds"

# Custom configuration for the AWS S3 client
[default.s3_storage]
bucket = "test-bucket"
endpoint = "https://127.0.0.1:4566"
access_key_id = "test"
secret_access_key = "test"
