[package]
name = "pki"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.5"
base64 = "0.22.0"
log = "0.4.21"
log4rs = "1.3.0"
openssl = "0.10.64"
serde = { version = "1.0.197", features = ["derive"] }
tokio = { version = "1.37.0", features = ["full"] }
utoipa = { version = "4.2.0", features = ["axum_extras", "yaml"] }
utoipa-swagger-ui = { version = "6.0.0", features = ["axum"] }
warp = "0.3.7"
