# Copyright (C) 2024 Nicola Dardanis <nicdard@gmail.com>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, version 3.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <https://www.gnu.org/licenses/>.
#
---
version: '3.7'
services:

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4510-4599:4510-4599"   # services port range
    environment:
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      DOCKER_HOST: unix:///var/run/docker.sock
      SERVICES: s3,dynamodb
      #DEBUG: 1
    volumes:
      - "./aws/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"  # ready hook

  mysql:
    # To exec into the container: docker exec -it mysql bash -l
    image: mysql:8.0
    container_name: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      # MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      # MYSQL_USER: test
      # MYSQL_PASSWORD: test
    volumes:
      # https://hub.docker.com/_/mysql (Initializing a fresh instance)
      - "./sql/:/docker-entrypoint-initdb.d/"
